import { StyleSheet } from 'react-native'
import { brandColors, brandShadow, radiusScale } from '~/design-system/tokens'
import { s, fs } from '~/utils/responsive'
import { Fonts } from '~/assets/config'

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: brandColors.background,
    },
    contentContainer: {
        padding: s(20),
        alignItems: 'center',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: s(20),
    },
    errorText: {
        fontSize: fs(14),
        color: brandColors.danger,
        textAlign: 'center',
        marginBottom: s(20),
    },
    ctaButton: {
        borderRadius: s(radiusScale.xl),
        overflow: 'hidden',
        minWidth: s(200),
        marginBottom: s(10),
    },
    ctaGradient: {
        height: s(48),
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: s(24),
    },
    ctaText: {
        color: brandColors.surface,
        fontSize: fs(13.5),
        fontFamily: Fonts.bold,
        fontWeight: '700',
    },
    cancelButtonOutline: {
        borderRadius: s(radiusScale.xl),
        minWidth: s(200),
        height: s(48),
        borderWidth: 1,
        borderColor: brandColors.borderSoft,
        backgroundColor: brandColors.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonOutlineFull: {
        width: '100%',
        borderRadius: s(radiusScale.xl),
        height: s(48),
        borderWidth: 1,
        borderColor: brandColors.borderSoft,
        backgroundColor: brandColors.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelText: {
        color: brandColors.muted,
        fontSize: fs(13.5),
        fontWeight: '700',
    },
    title: {
        fontSize: fs(16),
        fontFamily: Fonts.bold,
        fontWeight: '700',
        marginBottom: s(20),
        color: brandColors.textDark,
        textAlign: 'center',
    },
    qrContainer: {
        padding: s(20),
        backgroundColor: brandColors.surface,
        borderRadius: s(radiusScale.xxl),
        borderWidth: 1,
        borderColor: brandColors.borderSoft,
        marginBottom: s(24),
        ...brandShadow.soft,
    },
    infoContainer: {
        width: '100%',
        backgroundColor: brandColors.surface,
        borderWidth: 1,
        borderColor: brandColors.borderSoft,
        borderRadius: s(radiusScale.xxl),
        padding: s(16),
        marginBottom: s(20),
        ...brandShadow.soft,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: s(12),
    },
    infoLabel: {
        fontSize: fs(12.5),
        color: brandColors.muted,
        flex: 1,
    },
    infoValue: {
        fontSize: fs(12.5),
        color: brandColors.textDark,
        fontWeight: '700',
        flex: 1,
        textAlign: 'right',
    },
    amountText: {
        fontSize: fs(15),
        color: brandColors.tealDark,
        fontWeight: '800',
    },
    contentText: {
        fontSize: fs(11.5),
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: brandColors.tealLight,
        padding: s(12),
        borderRadius: s(radiusScale.lg),
        marginBottom: s(20),
        width: '100%',
    },
    statusText: {
        marginLeft: s(12),
        fontSize: fs(12.5),
        color: brandColors.tealDark,
        fontWeight: '600',
    },
    instructionContainer: {
        width: '100%',
        backgroundColor: 'rgba(245,166,35,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(245,166,35,0.25)',
        borderRadius: s(radiusScale.xxl),
        padding: s(16),
        marginBottom: s(20),
    },
    instructionTitle: {
        fontSize: fs(13.5),
        fontFamily: Fonts.bold,
        fontWeight: '700',
        color: brandColors.textDark,
        marginBottom: s(10),
    },
    instructionText: {
        fontSize: fs(12.5),
        color: brandColors.muted,
        lineHeight: fs(20),
    },
})
