import { Platform, StyleSheet } from 'react-native'
import Colors from '~/common/Colors/Colors'
import dimension from '~/constants/dimens'
import { s, fs } from '~/utils/responsive'
import { brandColors, liquidGlass, brandShadow } from '~/design-system/tokens'
import { Fonts } from '~/assets/config'

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: s(4),
  },
  imagePaginationContainer: {
    height: 24,
    width: 50,
    borderRadius: 35,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
    right: dimension.common.WINDOW_WIDTH / 2 - 12,
  },
  paginationNumber: {
    color: Colors.white,
    fontSize: 12,
  },
  swiperItemContainer: {
    backgroundColor: 'transparent',
    height: dimension.common.WINDOW_HEIGHT * 0.23,
    alignItems: 'center',
  },
  swiperItem: {
    width: dimension.common.WINDOW_WIDTH,
    height: dimension.common.WINDOW_WIDTH * 2 / 3,
  },
  productInfoContainer: {
    flex: 2,
    flexDirection: 'column',
    backgroundColor: 'rgba(255,255,255,0.42)',
    justifyContent: 'space-around',
    padding: s(18),
  },
  productContainer: {
    marginHorizontal: s(16),
    marginTop: s(10),
    marginBottom: s(12),
    backgroundColor: liquidGlass.background,
    borderRadius: s(24),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: liquidGlass.border,
    ...liquidGlass.shadow,
  },
  purchasePanel: {
    marginHorizontal: s(16),
    backgroundColor: liquidGlass.background,
    borderRadius: s(24),
    padding: s(18),
    borderWidth: 1,
    borderColor: liquidGlass.border,
    ...liquidGlass.shadow,
  },
  purchaseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    rowGap: s(14),
  },
  priceBlock: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: s(168),
    paddingRight: s(12),
  },
  amountBlock: {
    flexShrink: 0,
    alignItems: 'flex-end',
  },
  metaLabel: {
    color: brandColors.mutedLight,
    fontSize: fs(10),
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: s(4),
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: s(8),
  },

  quantityContainer: {
    display: 'flex',
    backgroundColor: liquidGlass.backgroundStrong,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: s(18),
    paddingBottom: 0
  },
  btnAddContainer: {
    margin: 0,
    flexDirection: 'row',
    paddingHorizontal: 0,
    marginHorizontal: 0,
    marginBottom: 0,
    marginTop: s(16),
  },
  btnAdd: {
    borderRadius: s(18),
    backgroundColor: brandColors.tealPrimary,
    flex: 1,
  },
  btnAddText: {
    fontSize: fs(14),
    fontWeight: '600',
  },
  // Sticky footer glass theo spec — thay cho nút "Thêm vào giỏ hàng" nằm
  // trong nội dung cuộn: hiện tổng tạm tính + CTA gradient, luôn cố định
  // dưới đáy màn hình.
  stickyFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(14),
    paddingHorizontal: s(20),
    paddingVertical: s(14),
    paddingBottom: s(20),
    backgroundColor: brandColors.surface,
    borderTopWidth: 1,
    borderTopColor: brandColors.border,
  },
  stickyFooterTotal: {
    flex: 1,
  },
  stickyFooterLabel: {
    fontFamily: Fonts.bold,
    fontWeight: 'normal',
    fontSize: fs(10),
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: brandColors.mutedLight,
  },
  stickyFooterAmount: {
    fontFamily: Fonts.bold,
    fontWeight: 'normal',
    fontSize: fs(16),
    color: brandColors.textDark,
  },
  stickyFooterButton: {
    flex: 1.4,
  },
  stickyFooterButtonGradient: {
    height: s(50),
    borderRadius: s(16),
    alignItems: 'center',
    justifyContent: 'center',
    ...brandShadow.button,
  },
  stickyFooterButtonText: {
    fontFamily: Fonts.bold,
    fontWeight: 'normal',
    fontSize: fs(15),
    color: brandColors.surface,
  },
  quantityBtnContainer: {
    flexDirection: 'row',
    margin: 0,
    padding: 0,
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  quantityBtn: {
    height: 36,
    width: 36,
    padding: 0,
    paddingHorizontal: 0,
    borderRadius: 36,
    backgroundColor: 'rgba(76, 29, 149,0.1)',
    borderWidth: 1,
    borderColor: liquidGlass.border,
  },
  productQuantityContainer: {
    borderRadius: 28,
    width: 84,
    marginHorizontal: 8,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: brandColors.muted,
  },
  inputContainerStyle: {
    display: 'flex',
    justifyContent: 'center',
    borderRadius: 28,
    alignItems: 'center',
  },
  labelStyle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productQuantity: {
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: brandColors.textDark,
  },
  title: {
    color: brandColors.textDark,
    fontWeight: '600',
    marginBottom: 6,
    marginRight: 18,
    fontSize: fs(16),
  },
  pack: {
    color: brandColors.muted,
    fontSize: fs(14),
    fontWeight: '600',
    lineHeight: 22,
  },
  sectiontitle: {
    fontSize: 14,
    fontWeight: '600',
    color: brandColors.textDark,
  },
  swiperConatainer: {
    backgroundColor: 'rgba(255,255,255,0.34)',
    height: (dimension.common.WINDOW_WIDTH - 36) * 2 / 3,
    marginBottom: 1,
  },
  priceInfoContainer: {
    flexDirection: 'row',
    backgroundColor: liquidGlass.backgroundStrong,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  priceContainer: {
    borderRadius: 36,
    borderColor: brandColors.goldAccent,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  productPrice: {
    color: brandColors.tealDark,
    fontSize: fs(24),
    fontWeight: '600',
    lineHeight: fs(32),
  },
  discount: {
    fontSize: fs(14),
    color: brandColors.mutedLight,
    fontWeight: 'normal',
    // lineHeight: 20,
    textDecorationLine: 'line-through',
    marginLeft: 0,
  },
  discountPercent: {
    marginLeft: s(10),
    color: brandColors.danger,
    fontSize: fs(13),
    fontWeight: '600',
  },
  actionCountContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  actionCountItemContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 18,
  },
  countValue: {
    marginLeft: 8,
  },
  rangePricesContainer: {
    flex: 1,
    padding: 18,
    backgroundColor: liquidGlass.background,
    marginBottom: 8,
    borderRadius: s(20),
    borderWidth: 1,
    borderColor: liquidGlass.border,
  },
  promotionTitle: {
    color: brandColors.textDark,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    marginBottom: 12,
  },
  infoSectionTitle: {
    color: brandColors.textDark,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
    marginBottom: 18,
    marginHorizontal: 18,
  },
  tabTitle: {
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 42,
    paddingVertical: 6,
    paddingHorizontal: 16,
    padding: 4,
    alignSelf: 'center',
  },
  tabSelected: {
    backgroundColor: liquidGlass.backgroundStrong,
    color: brandColors.tealPrimary,
    fontWeight: '600',
  },
  tabContainer: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'rgba(76, 29, 149,0.1)',
    borderRadius: 42,
    padding: 4,
    alignSelf: 'center',
    marginBottom: 18,
    borderWidth: 1,
    borderColor: liquidGlass.border,
  },
  tabText: {
    color: brandColors.textDark,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 22,
  },
  modalContainer: {
    flex: 1,
    width: dimension.common.WINDOW_WIDTH,
    height: dimension.common.WINDOW_HEIGHT,
  },
  buttonClose: {
    position: 'absolute',
    top: Platform.OS == 'android' ? 10 : 50,
    left: 10,
  },
})
