import { StyleSheet } from 'react-native'
import Colors from '~/common/Colors/Colors'
import { s, fs } from '~/utils/responsive'
import { brandColors, brandShadow, liquidGlass } from '~/design-system/tokens'
import { Fonts } from '~/assets/config'

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  backgroundImage: {
    flex: 1,
    backgroundColor: brandColors.background,
  },
  backgroundImageAsset: {
    width: '100%',
    height: '100%',
    opacity: 0,
  },
  backgroundBrightener: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
  },
  container: {
    backgroundColor: 'transparent',
    flexDirection: 'column',
    display: 'flex',
    justifyContent: 'flex-start',
    flex: 1,
  },
  contentLayer: {
    flex: 1,
  },
  supplierContentLayer: {
    paddingTop: s(142),
  },
  marketHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    paddingHorizontal: s(16),
    paddingTop: s(8),
    paddingBottom: s(10),
    backgroundColor: 'transparent',
  },
  marketHeaderScrim: {
    position: 'absolute',
    top: -s(80),
    left: 0,
    right: 0,
    height: 0,
  },
  marketHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: s(10),
    zIndex: 2,
  },
  brandMark: {
    width: s(42),
    height: s(42),
    borderRadius: s(18),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: liquidGlass.background,
    borderWidth: 1,
    borderColor: liquidGlass.border,
    overflow: 'hidden',
    ...liquidGlass.shadow,
  },
  brandLogo: {
    width: s(40),
    height: s(40),
  },
  brandCopy: {
    flex: 1,
    marginLeft: s(12),
  },
  headerEyebrow: {
    fontFamily: Fonts.semiBold,
    fontSize: fs(16),
    lineHeight: fs(21),
    fontWeight: 'normal',
    letterSpacing: 2.2,
    color: brandColors.tealDark,
  },
  headerTitle: {
    marginTop: s(1),
    fontFamily: Fonts.semiBold,
    fontSize: fs(12),
    lineHeight: fs(16),
    fontWeight: 'normal',
    color: brandColors.muted,
  },
  cartTouch: {
    width: s(48),
    height: s(48),
    borderRadius: s(20),
    overflow: 'visible',
  },
  cartPill: {
    width: '100%',
    height: '100%',
    borderRadius: s(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(11,123,138,0.18)',
  },
  cartBadge: {
    position: 'absolute',
    top: -s(6),
    right: -s(6),
    minWidth: s(22),
    height: s(22),
    borderRadius: s(11),
    paddingHorizontal: s(5),
    backgroundColor: brandColors.danger,
    borderWidth: 2,
    borderColor: brandColors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    fontFamily: Fonts.semiBold,
    fontSize: fs(11),
    lineHeight: fs(14),
    fontWeight: 'normal',
    color: brandColors.surface,
  },
  searchTouch: {
    flex: 1,
    marginTop: 0,
    borderRadius: s(27),
    zIndex: 2,
    overflow: 'visible',
  },
  searchDock: {
    minHeight: s(48),
    borderRadius: s(24),
    backgroundColor: 'rgba(255,255,255,0.94)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(14),
    borderWidth: 1,
    borderColor: 'rgba(11,123,138,0.08)',
    shadowColor: '#0A2F38',
    shadowOpacity: 0.08,
    shadowRadius: s(14),
    shadowOffset: { width: 0, height: s(7) },
    elevation: 3,
  },
  searchIconBubble: {
    width: s(26),
    height: s(34),
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  searchTextWrap: {
    flex: 1,
    marginLeft: s(8),
  },
  searchLabel: {
    fontFamily: Fonts.semiBold,
    fontSize: fs(9),
    lineHeight: fs(12),
    fontWeight: 'normal',
    letterSpacing: 1.2,
    color: brandColors.goldAccent,
    textTransform: 'uppercase',
  },
  searchText: {
    fontFamily: Fonts.semiBold,
    fontSize: fs(15),
    lineHeight: fs(20),
    fontWeight: 'normal',
    color: 'rgba(26,26,46,0.54)',
  },
  headerMetrics: {
    marginTop: s(10),
    minHeight: s(42),
    borderRadius: s(16),
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: s(10),
  },
  metricItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    fontFamily: Fonts.semiBold,
    fontSize: fs(13),
    lineHeight: fs(17),
    fontWeight: 'normal',
    color: brandColors.surface,
  },
  metricLabel: {
    marginTop: 0,
    fontFamily: Fonts.semiBold,
    fontSize: fs(9),
    lineHeight: fs(12),
    fontWeight: 'normal',
    color: 'rgba(255,255,255,0.68)',
  },
  metricDivider: {
    width: 1,
    height: s(22),
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  distributors: {
    paddingHorizontal: s(12),
    paddingVertical: s(10),
    backgroundColor: 'transparent',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  listDistributors: {
    flexGrow: 0,
    backgroundColor: 'transparent',
    marginBottom: s(2),
  },
  viewContent: {
    backgroundColor: brandColors.surface,
    padding: s(20),
    height: s(300),
    justifyContent: 'space-around',
    alignItems: 'center',
    borderRadius: s(24),
    ...brandShadow.soft,
  },
  image: {
    height: s(120),
    width: s(120)
  },
  buttonUpdate: {
    padding: s(10),
    height: s(50),
    backgroundColor: Colors.colorMain
  },
  textUpdate: {
    color: brandColors.surface
  },
  textVerApp: {
    fontSize: fs(16),
    textAlign: 'center',
    marginTop: s(5),
    color: brandColors.textDark,
  }
})
