import { StyleSheet } from 'react-native'
import { s, fs } from '~/utils/responsive'
import { brandColors, liquidGlass } from '~/design-system/tokens'

const styles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    paddingBottom: s(112),
  },
  heroCard: {
    marginHorizontal: s(16),
    marginTop: s(12),
    paddingHorizontal: s(18),
    paddingVertical: s(16),
    borderRadius: s(24),
    backgroundColor: liquidGlass.backgroundStrong,
    borderWidth: 1,
    borderColor: liquidGlass.border,
  },
  heroEyebrow: {
    fontSize: fs(10),
    lineHeight: fs(14),
    fontWeight: '600',
    letterSpacing: 1.4,
    color: brandColors.tealPrimary,
  },
  heroTitle: {
    marginTop: s(6),
    fontSize: fs(22),
    lineHeight: fs(28),
    fontWeight: '600',
    color: brandColors.textDark,
  },
  heroSubtitle: {
    marginTop: s(8),
    fontSize: fs(12),
    lineHeight: fs(18),
    fontWeight: '600',
    color: brandColors.muted,
  },
  filterCard: {
    marginHorizontal: s(16),
    marginTop: s(12),
    paddingBottom: s(14),
    borderRadius: s(24),
    backgroundColor: liquidGlass.background,
    borderWidth: 1,
    borderColor: liquidGlass.border,
  },
  groupContainer: {
    paddingHorizontal: s(18),
    marginTop: s(18),
    display: 'flex',
    flexDirection: 'column',
  },
  groupTitle: {
    color: brandColors.textDark,
    fontWeight: '600',
    fontSize: fs(17),
    lineHeight: fs(24),
  },
  groupSubTitle: {
    color: brandColors.muted,
    fontWeight: '600',
    fontSize: fs(12),
    lineHeight: fs(18),
    marginTop: s(2),
    marginBottom: s(10),
  },
  groupItemContrainer: {
    width: '48%',
    minWidth: 0,
  },
  groupItemGlass: {
    minHeight: s(58),
    paddingHorizontal: s(10),
    paddingVertical: s(10),
    borderRadius: s(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupItem: {
    textAlign: 'center',
    color: brandColors.muted,
    fontWeight: '600',
    fontSize: fs(12),
    lineHeight: fs(17),
  },
  groupItemSelected: {
    color: brandColors.surface,
    fontWeight: '600',
  },
  groupListItemContainer: {
    display: 'flex',
    marginVertical: s(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  checkMark: {
    position: 'absolute',
    right: s(8),
    top: s(8),
    width: s(18),
    height: s(18),
    borderRadius: s(9),
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  showMore: {
    color: brandColors.tealPrimary,
    fontWeight: '600',
    fontSize: fs(13),
    lineHeight: fs(18),
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(18),
    paddingTop: s(12),
    paddingBottom: s(28),
    backgroundColor: 'rgba(245,252,253,0.76)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.82)',
    ...liquidGlass.shadow,
  },
  buttonConfirm: {
    flex: 1,
    paddingHorizontal: s(6),
  },
  resetButton: {
    minHeight: s(52),
    borderRadius: s(18),
    backgroundColor: liquidGlass.backgroundStrong,
    borderColor: brandColors.tealPrimary,
    borderWidth: 1,
  },
  resetButtonText: {
    fontWeight: '600',
    color: brandColors.tealPrimary,
  },
  applyButton: {
    minHeight: s(52),
    borderRadius: s(18),
    backgroundColor: brandColors.tealPrimary,
  },
})
export default styles
